apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-observability-extras-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/David-Uka/cluster-observability.git
    targetRevision: main
    path: manifests/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
